version: '3'
services:
  backend:
    build:
     context: .
     dockerfile: Dockerfile
    image: nodejs_project
    container_name: backend
    restart: unless-stopped
    env_file: .env
    environment:
      - API_BASE_URL=$API_BASE_URL
      - API_KEY_NAME=$API_KEY_NAME
      - API_KEY_VALUE=$API_KEY_VALUE
      - PORT=$PORT
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    

